- packages/element/src/runtime/EvaluatedScript.ts
- smoke/test-scripts/short-csv.fail.ts
- smoke/test-scripts/short-csv.fail/data.csv
- smoke/test-scripts/suite.pass.ts
re-adds `suite` and `suite.withData`
> reenable suite

- packages/element/docs/examples/examples_element_cli.md
> Examples/docs for Element CLI

- packages/element/docs/examples/scenario_1_wordpress.md
Change jriz.io to wordpress.loadtest.io as this will be the new location of the shop
> Changes to deep dive for new loadtest.io page

- packages/core/src/page/conditions/URLNotMatchCondition.ts
Clean an unused import in previous PR that break CI
> chore: remove unused import

- extern/dogfood/dockerfiles/watirspec/html/page_1.html
- extern/dogfood/dockerfiles/watirspec/html/page_2.html
- packages/core/src/page/TargetLocator.ts
- packages/core/src/runtime/Browser.spec.ts
- packages/core/src/runtime/Browser.ts
- packages/core/src/runtime/types.ts
> Revert "Handle multiple Tabs/Windows"

- extern/dogfood/dockerfiles/watirspec/html/page_1.html
- extern/dogfood/dockerfiles/watirspec/html/page_2.html
- packages/core/src/page/TargetLocator.ts
- packages/core/src/runtime/Browser.spec.ts
- packages/core/src/runtime/Browser.ts
- packages/core/src/runtime/types.ts
> Revert "Feature/multi tabs or windows (with fixing CI/CD error)"

- packages/core/src/page/conditions/DialogCondition.ts
- packages/core/src/page/conditions/FrameCondition.ts
> fix: through error when running debug mode on windows #151

- packages/cli/src/cmd/generate.ts
> fix: Unable to use the command line: generate <file.ts> #165

- .vscode/launch.json
- packages/core/src/runtime/Test.ts
> bugfix: Fix issue of step repeat in recovery mode

- packages/core/src/runtime/Test.ts
> bugfix: setting `recoveryTries` does not work

- examples/condition/test.ts
- packages/core/src/runtime/EvaluatedScript.ts
- packages/core/src/runtime/EvaluatedScriptLike.ts
- packages/core/src/runtime/Settings.ts
- packages/core/src/runtime/Step.ts
- packages/core/src/runtime/Test.spec.ts
- packages/core/src/runtime/Test.ts
> Features/global recovery step #181

- packages/core/src/page/TargetLocator.ts
Currently, a frame cannot be found if its name is empty and we find it by `ElementHandle`. In that case, we find it from `window.frames`
resolve #182
> Frame not found if its name is empty & is found by ElementHandle

- examples/the-internet-more-examples/tables.ts
This PR includes example scripts below:
```
Until.elementTextDoesNotMatch(selectorOrLocator: NullableLocatable, regex: RegExp)
Until.titleIs(title: string)
Until.urlIs(url: string)
By.js(script: EvaluateFn, ...args: any[])
ElementHandle.findElements(locator: Locator | string)
```
> [FLO-1756] Example scripts at the-internet/tables

- examples/the-internet-more-examples/redirector.ts
This PR includes example scripts below:
```
By.linkText(text: string)
ElementHandle.takeScreenshot()
ElementHandle.getId()
Browser.mouse.click()
Browser.waitForNavigation()
Browser.evaluate(fn: EvaluateFn)
```
> [FLO-1756] Example scripts at the-internet/redirector

- examples/the-internet-more-examples/dropdown.ts
This PR includes example scripts below:
```
Browser.selectByText(locatable: NullableLocatable, text: string)
Browser.takeScreenshot(options?: ScreenshotOptions)
Browser.setViewport(viewport: Viewport)
```
> [FLO-1756] Example scripts at the-internet/dropdown

- extern/dogfood/dockerfiles/watirspec/html/wait.html
- package.json
- packages/core/src/page/ElementHandle.spec.ts
- packages/core/src/page/ElementHandle.ts
- packages/core/src/page/Mouse.ts
- packages/core/src/page/conditions/ElementSelectedCondition.ts
- packages/core/src/runtime/Step.ts
Fix the following bugs:
- ElementHandle.isSelected() always false
- ElementHandle.isSelectable() always false
- ElementSelectedCondition's pageFunc always returns false
- step that has data in TestFn is not defined
- Mouse.click's overloads behave differently
> fix: fix several bugs found on element api

- examples/flood-element-challenge.ts
This PR includes example scripts below
```
By.css(selector: string, debugString?: string)
ElementHandle.location()
Mouse.click(x: number, y: number, options: ClickOptions)
Mouse.down(option?: MousePressOptions)
Mouse.up(option?: MousePressOptions)
Mouse.move(x: number, y: number, options?: {steps: number})
Mouse.drag(from: Point, to: Point)
Browser.wait(timeoutOrCondition: Condition | number)
```
> [FLO-1757] Example scripts for context menu, drag and drop

- scripts/publish-brew-tap/index.ts
> Revert "fix: error publishing release to Homebrew"

- packages/core/src/page/TargetLocator.ts
> revert: find frame from current window if not found from current page

- packages/docs/docs/guides/CLI.md
- packages/docs/docusaurus.config.js
- packages/docs/src/components/Header/styles.module.css
- packages/docs/src/components/Main/FeatureBlock/styles.module.css
- packages/docs/src/css/custom.css
- yarn.lock
- Adds Algolia search
- Cleans up styles
> Fixes style and search

- packages/cli/src/cmd/run.ts
- packages/cli/src/utils/ConsoleReporter.ts
> Revert "bugfix: minors issue of element 1.3"

- examples/hook/package.json
- lerna.json
- package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/compiler/CHANGELOG.md
- packages/compiler/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/docs/CHANGELOG.md
- packages/docs/package.json
- packages/element-api/CHANGELOG.md
- packages/element-api/package.json
- packages/element-cli/CHANGELOG.md
- packages/element-cli/package.json
- packages/element/CHANGELOG.md
- packages/element/package.json
- packages/flood-runner/CHANGELOG.md
- packages/flood-runner/package.json
> fix: bump 1.3.1

- packages/cli/src/cmd/run.ts
- packages/core/src/Looper.ts
- packages/core/src/Runner.ts
- packages/flood-runner/src/Grid.ts
**Note:** This PR also changes the fail status code for tests to 0 when running on Grid
> fix: element run with --watch option is not working

- .github/workflows/lerna-beta.yml
- .github/workflows/lerna-stable.yml
> Revert "fix: brew release workflows"

- .github/workflows/lerna-beta.yml
- .github/workflows/lerna-stable.yml
> Revert "fix: error publishing Element to Homebrew"

- packages/element-scheduler/src/Scheduler.ts
> Revert "[Bugfix][FLO-1865] Element version shows an error"

- lerna.json
Edit `lerna.json` to specify the exact version of dependencies of packages.
> [Element 2.0] Specify the exact version of dependencies

- packages/core/src/page/ElementHandle.ts
- packages/core/src/page/Locator.ts
- packages/core/src/page/TargetLocator.ts
- packages/core/src/page/types.ts
- packages/core/src/runtime/Browser.ts
> fix: cannot swith to a frame by Browser.switchTo()

- examples/flood-element-challenge.ts
- examples/scroll/scrollTo.perf.ts
- extern/dogfood/dockerfiles/watirspec/html/scroll.html
- packages/core/src/page/types.ts
- packages/core/src/runtime/Browser.spec.ts
- packages/core/src/runtime/Browser.ts
- packages/core/src/runtime/IBrowser.ts
Implementing new API for Element.
**browser.scrollBy(x: number, y: number, [,option])**
```
- x: How many pixels to scroll by, along the x-axis (horizontal). Positive values will scroll to the right, while negative values will scroll to the left. 
- x can take window.innerWidth as a special value.
- y: How many pixels to scroll by, along the y-axis (vertical). Positive values will scroll down, while negative values scroll up.
- y can take window.innerHeight as a special value.
- option: is an object containing ScrollToOptions.
E.g.: 
await browser.scrollBy(100, 0, { behavior: 'smooth' })
await browser.scrollBy('window.innerWidth', 0, { behavior: 'smooth' })
await browser.scrollBy(0, 'window.innerHeight', { behavior: 'smooth' })
const innerHeight: number = await browser.evaluate(() => …
```
> [Element 1.4] Implement new API browser.scrollBy() and browser.scrollTo()

- packages/cli/package.json
- packages/core/src/network/Recorder.spec.ts
- packages/core/src/runtime/EvaluatedScript.ts
- packages/core/src/runtime/Test.ts
- packages/core/src/test-data/Feeder.spec.ts
- packages/core/src/test-data/Feeder.ts
- packages/core/src/test-data/Loader.ts
- packages/core/src/test-data/TestData.ts
- packages/core/src/test-data/TestDataLoaders.spec.ts
- packages/core/src/test-data/TestDataLoaders.ts
- packages/core/tests/fixtures/data/diff_users.csv
- packages/core/tests/fixtures/data/diff_users.json
- packages/core/tests/fixtures/data/orders.csv
- packages/core/tests/fixtures/data/users.json
- packages/core/tests/fixtures/data/users_same.csv
- packages/core/tests/fixtures/data/users_same.json
- packages/flood-runner/README.md
- yarn.lock
resolve https://tricentisflood.atlassian.net/browse/FLO-1900
> [Element 1.4] Support multiple data files in a single test script

- lerna.json
- packages/core/src/network/Recorder.spec.ts
Edit file lerna.json:
```
- Add option ignoreChanges: ["*.md", "packages/docs/**"] into command.publish.
- Add `**/*md, packages/docs/**` to property ignoreChanges.
```
> [Element 2.0] Prevent auto bumping version when modifying docs (**/*.md & packages/docs/**)

- examples/condition/test.ts
- packages/core/src/runtime/StepIterator.ts
- packages/core/src/runtime/test-observers/LifecycleObserver.ts
- packages/flood-runner/src/Grid.ts
resolve https://tricentisflood.atlassian.net/browse/FLO-1938
> [Element 1.3] The number of transactions reported was incorrect when running tests on flood

- .github/workflows/lerna-beta.yml
Add a flag `--ignore-changes` into the publish command at lerna-beta.yml.
> [Element 2.0 ] Prevent auto bumping version when modifying docs beta

- packages/core/src/runtime/Browser.ts
- packages/core/src/runtime/decorators/autoWait.ts
I've created new functions without the decorator, and call it from the original function. I also edited the decorator `autoWaitUntil`.
> [Element 2.0] Create consistency between browser's actions of script and reporter

- packages/core/src/Looper.ts
- packages/core/src/runtime/StepIterator.ts
resolve https://tricentisflood.atlassian.net/browse/FLO-1995
> [Element 1.4] Fix issue of step.recovery and step.while

- packages/core/src/runtime/StepIterator.ts
> [Element 2.0] Using optional chainning to check object is not null or undefined

- .github/workflows/lerna-stable.yml
- CHANGELOG.md
- lerna.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/compiler/CHANGELOG.md
- packages/compiler/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/docs/CHANGELOG.md
- packages/docs/package.json
- packages/element-api/CHANGELOG.md
- packages/element-api/package.json
- packages/element-cli/CHANGELOG.md
- packages/element-cli/package.json
- packages/element/CHANGELOG.md
- packages/element/package.json
- packages/flood-runner/CHANGELOG.md
- packages/flood-runner/package.json
This PR is created to fix the correct version of Element@beta (from **1.3.10-beta.0** to **1.4.0-beta.4**)
> [Element Beta 1.4] Fix the correct version of packages

- packages/core/src/test-data/Feeder.ts
resolve https://tricentisflood.atlassian.net/browse/FLO-2049
> [Element 1.4] Cannot read property 'indexOf' of undefined" when running multiple test data

- packages/cli/src/cmd/run.ts
This PR is going to fix the issue [FLO-2082](https://tricentisflood.atlassian.net/browse/FLO-2082).
> [Element 2.0] Can not run a single test script without the config file

- packages/cli/templates/test.ts
Relate to the issue [Issue #334](https://github.com/flood-io/element/issues/334) and [FLO-2110](https://tricentisflood.atlassian.net/browse/FLO-2110)
> [Element 2.0] The init command does not create a valid test script

- examples/using-test-data/flooders-part-1.json
- examples/using-test-data/flooders-part-2.json
- examples/using-test-data/multi-test-data.perf.ts
- examples/using-test-data/users.csv
- packages/core/src/runtime/EvaluatedScript.ts
- packages/core/src/runtime/Test.ts
- packages/core/src/test-data/Feeder.spec.ts
- packages/core/src/test-data/Feeder.ts
- packages/core/src/test-data/Loader.ts
- packages/core/src/test-data/TestData.ts
- packages/core/src/test-data/TestDataLoaders.spec.ts
- packages/core/src/test-data/TestDataLoaders.ts
- packages/core/tests/fixtures/data/diff_users.csv
- packages/core/tests/fixtures/data/diff_users.json
- packages/core/tests/fixtures/data/orders.csv
- packages/core/tests/fixtures/data/users.json
- packages/core/tests/fixtures/data/users_same.csv
- packages/core/tests/fixtures/data/users_same.json
Based on [this PR](https://github.com/flood-io/element/pull/308)
> [Element 2.0] Implement multiple test data from element 1.5 to 2.0

- packages/core/src/interface/IBrowser.ts
- packages/core/src/runtime/Browser.ts
- packages/report/src/reporters/Base.ts
Base on [this PR](https://github.com/flood-io/element/pull/328)
> [Element 2.0] Implement api getMimeType from version 1.5 to 2.0

- packages/core/src/Runner.ts
resolve https://tricentisflood.atlassian.net/browse/FLO-2153
> [Element 2.0] Report table does not show on error

- packages/docs/docs/start/install.md
- packages/docs/versioned_docs/version-1.0/start/install.md
- packages/docs/versioned_docs/version-1.3/start/install.md
- packages/docs/versioned_docs/version-1.5/start/install.md
Simple update to the documentation re installing via homebrew
> fix: update brew install instructions

- packages/core/src/page/ElementHandle.spec.ts
- packages/core/src/runtime/Browser.ts
- packages/core/src/runtime/EvaluatedScript.spec.ts
- packages/core/src/test-script/WebpackCompiler.ts
- tsconfig.json
This PR resolves comments of [the release PR](https://github.com/flood-io/element/pull/421).
> [Element 2.0] Resolve comment of the release PR

- packages/core/src/Runner.ts
- packages/core/src/runtime/Browser.ts
Relate to this issue [FLO-2177](https://tricentisflood.atlassian.net/browse/FLO-2177)
> [Element 2.0] Show warning of inapplicable functionality for firefox and webkit

- packages/cli/templates/element.config.js
Base on the suggestion of Ivan on [this PR](https://github.com/flood-io/element/pull/421)
Relate to [this issue](https://tricentisflood.atlassian.net/browse/FLO-2183)
> [Element 2.0] Add unique suffix (.perf.ts) to testPathMatch of the template of Element config

- packages/docs/versioned_docs/version-2.0/start/install.md
We no longer support installing from brew
> Remove brew install from docs

- packages/cli/src/utils/updateCheck.ts
Resolve this issue [**FLO-2208**](https://tricentisflood.atlassian.net/browse/FLO-2208)
Just a little fixing base on the usage of `command-exists` [here](https://www.npmjs.com/package/command-exists).
> [Element 1.x.x] Resolve unhandled rejection on Windows and Ubuntu

- .github/workflows/ci.yml
- packages/core/src/utils/ObjectTrace.spec.ts
Resolve issue [**FLO-2209**](https://tricentisflood.atlassian.net/browse/FLO-2209)
> [Element 2.0] Fix unit test of Object Trace

- lerna.json
- package.json
- packages/cli/package.json
- packages/compiler/package.json
- packages/core/package.json
- packages/docs/package.json
- packages/element-api/package.json
- packages/element-cli/package.json
- packages/element-scheduler/package.json
- packages/element/package.json
- packages/flood-runner/package.json
- packages/report/package.json
I fixed the version of canary packages to make sure the Github Actions can publish it to the canary channel.
> [Element Canary] Fix version of canary packages

- packages/core/src/runtime/test-observers/LifecycleObserver.ts
- packages/flood-runner/src/Grid.ts
This commit brings across the fix that was made in #319, looks like it was lost in some merge.
> Fix 3x reported transaction rate in 2.x

- packages/cli/src/index.ts
- packages/cli/src/utils/updateCheck.ts
Fixing the build so we can publish 1.5.x again
> fix: remove update check in a different way
