packages/element/src/runtime/Browser.ts
packages/element/src/runtime/Settings.ts
packages/element/src/runtime/Test.ts
packages/element/src/runtime/types.ts

Simple facility for setting custom http headers.
WIP because I'm not quite sure how to test.
Need a repeatable site like `challenge.flood.io` to test this from a smoke test.
I tried setting User-Agent, but you need to do that via `setUserAgent`.

WIP custom http headers

---

examples/proxy-settings/test.ts
packages/element/src/Runner.ts
packages/element/src/driver/Puppeteer.ts
packages/element/src/runtime/Settings.ts
packages/element/src/runtime/Test.spec.ts
yarn.lock

Adds support for applying additional launch args to Chrome. 
```ts
export const settings: TestSettings = {
launchArgs: ['--proxy-server=127.0.0.1:9876']
}
```
For a complete list of args, see https://peter.sh/experiments/chromium-command-line-switches/
Closes #78

Feat: Additional launch args

---

packages/cli/src/cmd/run.ts

when executing the cmd: `element run file.ts`, the `loopCount` always has default value is 1 and it overrides the one which was defined in `TestSetting`. So the fix do the following:
- if the cmd does NOT included the `--loop-count` option, do not set default value is 1 and use the `loopCount` value defined in the TestSetting. If TestSetting does not define `loopCount`, the test will loop infinitely
- if the cmd included `--loop-count` option, it overrides the current one in the TestSetting.
resolves #91 
It seems we do not add `.editorconfig` file so when viewing the ts file, the indent is not right.

[bugfix] Loop Count setting does not work

---

examples/screenshot-on-failure/screenshot-on-failure.ts
packages/core/src/runtime/test-observers/Errors.ts

Fix `screenshotOnFailure: true` not working 
Screenshot of errors have prefix `error_<stepName>_`
Resolves #87 
Result with example:

Fix screenshot on failure not working

---

packages/core/src/page/Until.ts
packages/core/src/page/conditions/ElementTextNotMatchCondition.spec.ts
packages/core/src/page/conditions/ElementTextNotMatchCondition.ts

Added features:
- Until.elementTextIsNot() - Full text not match comparison
- Until.elementTextDoesNotMatch() - Regex not match comparison
Solve a part of feature request in #37 
Remaining feature request in #37 : 
- titleDoesNotMatch(title)
- urlDoesNotMatch(title)
Since they're waiters in different object so I'll have another PR for those 2
Considering
- Until.elementTextDoesNotContain()
=> Use case: Changing only a part of text, like page visit counter increment (but this one can be solved with regex)
Note: please squash merge :D

feat: text not match waiters

---

packages/cli/src/cmd/agent/start.ts
packages/cli/src/cmd/run.ts
packages/core/api.ts
packages/core/src/Element.ts
packages/core/src/Runner.ts
packages/core/src/runtime/ITest.ts
packages/core/src/runtime/Test.ts
packages/element-api/index.ts
packages/flood-runner/src/Grid.ts

User can pass in the option **fail-status-code** to the command `element run test.ts` to be the exit code when the test fails, otherwise exit code is 0.
resolve #30

Allow user to specify a return code when the test fails

---

packages/core/src/runtime/Browser.ts

Make `browser.visit()` return the response instead of throw error when response is null or response code is not in 200 -> 299 or 300 -> 399
resolve #146

Fix: Element expected a response code 200-299 or 300-399

---

examples/internet-herokuapp/33-Multiple_Windows.ts
packages/core/src/runtime/Browser.ts

- Fix: Cannot switch to a new tab if the current tab contains a frame
- Update the example for handling multiple tabs

Fix: Handle multiple tabs that contain frame

---

packages/flood-runner/package.json
yarn.lock

Package `flood-runner` is using an old version of `element-core` (version `1.2.3-beta.4`) which is incompatible with the current latest version `1.3.0-beta.19` (class `NetworkRecordingTestObserver` is not defined in version `1.2.3-beta.4`).
This PR update the version of `element-core` which `flood-runner` is using to the latest.

fix: Class extends value undefined is not a constructor or null (class TracingObserver extends NetworkRecordingTestObserver)

---

examples/flood-io.ts
examples/mozilla-demos.ts
examples/the-internet-more-examples/frames.ts

This PR includes the example scripts below:
```
Until.ableToSwitchToFrame(frame: Locator)
Until.titleContains(title: string)
Until.urlContains(url: string)
By.nameAttr(value: string)
ElementHandle.clear()
ElementHandle.type(text: string)
ElementHandle.blur()
ElementHandle.highlight()
TargetLocator.activeElement()
TargetLocator.frame(id: number | string | ElementHandle)
Browser.doubleClick(locatable: NullableLocatable, options?: ClickOptions)
```

[FLO-1756] Element - More example scripts - frames

---

.github/workflows/lerna-beta.yml
.github/workflows/lerna-stable.yml

- Add the flag `--force-publish` to the command `lerna publish` so that every package has its version bumped even when it was not modified
- Add the script for publishing the release to Homebrew from the workflows

chore: force all packages to have the same version + auto publish to brew

---

packages/cli/src/cmd/run.ts
packages/cli/src/utils/ConsoleReporter.ts

fix some minor issues:
- Resolve issue https://spectrum.chat/flood/element/cannot-call-getcomponentdata-on-component~886b4dac-338b-4984-bd01-b74a5d6b1c74
- Setting `stepDelay` and `actionDelay` don't work

bugfix: minors issue of element 1.3

---

packages/cli/src/cmd/run.ts
packages/cli/src/utils/ConsoleReporter.ts

Resolve those issues:
- https://spectrum.chat/flood/element/cannot-call-getcomponentdata-on-component~886b4dac-338b-4984-bd01-b74a5d6b1c74
- setting `actionDelay` and `stepDelay` does not work

Bugfix: Element 1.3

---

packages/cli/src/utils/flood.ts
packages/core/src/runtime/Test.ts

Fix the following things:
- Cannot authenticate with flood using an account member token
- Show error `recovery step -> failed` even when there's no recovery step

fix: some minor bugs

---

.github/workflows/lerna-beta.yml
.github/workflows/lerna-stable.yml

Using https://github.com/marketplace/actions/homebrew-tap in both stable and beta workflows to publish the release to Homebrew
**Note:**  Before this PR get merged, `secrets.GITHUB_TOKEN` and `secrets.TAP_GITHUB_TOKEN` need to be set in the env

fix: error publishing Element to Homebrew

---

packages/core/package.json

Hello!  This PR updates the CSV dependency to resolve [this upstream vulnerability](https://www.npmjs.com/advisories/1171).  Along the way, I realized that the entire `csv` module was a dependency, but only `csv-parse` was being used (`csv` includes `csv-parse` and a few others).  So this PR also swaps out `csv` for `csv-parse`.
There are no code changes required for this PR - it's a dependency only change.

Update csv-parse dependency to fix vulnerability

---

packages/core/src/Element.ts
packages/core/src/network/Interceptor.ts

- Change the API from `page.off()` to `page.removeListener()` to work compatible with Node v8.9+.
- Show the Element and Node version when running tests.

fix: change puppeteer API to unsubscribe from events

---

README.md
packages/cli/README.md
packages/cli/src/cmd/run.ts
packages/core/src/Element.ts
packages/core/src/Runner.ts
packages/core/src/network/Interceptor.ts
packages/docs/docs/api/ElementHandle.md
packages/docs/docs/api/TestData.md
packages/docs/docs/guides/CLI.md
packages/docs/docs/guides/TestData.md
packages/docs/docs/start/changelog.md
packages/docs/versioned_docs/version-1.0/guides/CLI.md
packages/docs/versioned_docs/version-1.3/api/ElementHandle.md
packages/docs/versioned_docs/version-1.3/guides/CLI.md
packages/docs/versioned_docs/version-1.3/guides/TestData.md
packages/docs/versioned_docs/version-1.3/start/changelog.md
packages/flood-runner/src/Grid.ts
yarn.lock

Fix: On Grids, tests stop running if there's a failed step, instead of skip to the next iteration.
Enhance: Show Node and Element version when running tests.

fix: handle fail exit code when running on local only

---

.github/workflows/lerna-beta.yml
.github/workflows/lerna-stable.yml
lerna.json
packages/cli/src/generator/test-env/index.ts

Add a flag `--exact` when publishing a new version of stable version and beta version to specify updated dependencies in updated packages **exactly** (with no punctuation), instead of as semver compatible **(with a ^)**.
More specifically, please take a look at [documentation of lerna](https://github.com/lerna/lerna/tree/master/commands/version#--exact).

[Element 1.4] Edit publish config to specify the exact version of updated dependencies

---

.github/workflows/lerna-beta.yml
.github/workflows/lerna-stable.yml
lerna.json

Edit file `lerna.json`:
- Add option `ignoreChanges: ["*.md", "packages/docs/**"]` into `command.publish`.
- Add `**/*md` & `packages/docs/**` to `ignoreChanges`.
For more information, please take a look at [Lerna.json](https://github.com/lerna/lerna#lernajson) and [lerna version --ignore-change](https://github.com/lerna/lerna/tree/master/commands/version#--ignore-changes)

[Element v1.4] Prevent Lerna auto-bumping version when modifying docs (*.md & packages/docs/**)

---

packages/core/src/runtime/Browser.spec.ts
packages/core/src/runtime/Browser.ts
packages/core/src/runtime/IBrowser.ts

**browser.getUrl()**
**Description**: Return the URL of the current page as a string.
**Params**: none
**Return**: current URL as a string

[Element 1.4] Introduce `browser.getUrl()` as new API

---

packages/core/src/runtime/Browser.ts

Change the default NavigationOptions's waitUntil from `['load', 'domcontentloaded', 'networkidle0', 'networkidle2']` to `'load'`

[Bugfix][Element 1.4] Change default NavigationOptions waitUntil of browser.visit

---

packages/core/src/runtime/Settings.ts
packages/core/src/runtime/Test.spec.ts

Set the default viewport of the browser is `1440 x 900` instead of `800 x 600`

[Element Canary] Set default viewport of client's browser

---

examples/flood-element-challenge.ts
packages/docs/docusaurus.config.js

Changed from: flood-element-challenge.vercel.app
To: https://element-challenge.flood.io/

docs: update link for Flood Element Challenge [skip-ci]

---

packages/core/src/page/ElementHandle.ts
packages/report/src/reporters/Base.ts
packages/report/src/reporters/Verbose.ts

**Before**
**After**
--------------------------------------------------------------------------------------------------------------------
**Before**
**After**

[Element 2.0] Enhance text color of terminal output

---

packages/core/src/Element.ts

Fix the issue that relates to [FLO-2106](https://tricentisflood.atlassian.net/browse/FLO-2106)

[Element 2.1] Remove the test path matched message when running single test script

---

examples/scroll/scrollTo.perf.ts
extern/dogfood/dockerfiles/watirspec/html/scroll.html
packages/cli/templates/test.ts
packages/core/src/Element.ts
packages/core/src/interface/IBrowser.ts
packages/core/src/page/types.ts
packages/core/src/runtime/Browser.spec.ts
packages/core/src/runtime/Browser.ts
packages/core/src/utils/CheckInstance.ts
packages/core/src/utils/StepActionArgs.ts

Apply features from version 1.4 to version 2.0. Relate to this issue: [FLO-1962](https://tricentisflood.atlassian.net/browse/FLO-1962)
```
- Print version of Element and Node when running test.
- Apply API browser.getUrl()
- Apply API browser.scrollTo(target: Locator | ElementHandle | Point | ScrollDirection, scrollOptions?: ScrollIntoViewOptions)
- Apply API browser.scrollBy(x: number | 'window.innerWidth', y: number | 'window.innerHeight',  scrollOptions?: ScrollOptions)
```

[Element 2.0] Apply features from version 1.4 to version 2.0

---

extern/dogfood/dockerfiles/watirspec/html/html_drag_drop.html
packages/core/package.json
packages/core/src/interface/IBrowser.ts
packages/core/src/page/ElementHandle.spec.ts
packages/core/src/page/ElementHandle.ts
packages/core/src/page/types.ts
packages/core/src/runtime/Browser.spec.ts
packages/core/src/runtime/Browser.ts
yarn.lock

Drag & drop an element into another element with 2 new methods:
- Browser.drag(from: ElementHandle, to: ElementHandle)
- ElementHandle.drag(to: ElementHandle)
**Note:** This only work with drag & drop using HTML drag & drop API

feat: drag & drop an element into another element

---

packages/flood-runner/src/Environment.ts

This change means `flood-runner` will run in a production environment unless explicitly setting `NODE_ENV` to development.

fix: flood-runner default to run in production env

---

packages/core/package.json

[Element 2.0] Move spinnies from devDependencies to Dependencies

---

packages/core/src/driver/Playwright.ts

Fix error: `Cannot parse arguments: Unknown option --disable-gpu` when running a test with `webkit` browser, on a flood-element docker container

fix: unknown option --disable-gpu

---

packages/cli/src/cmd/run.ts

[Element 2.0] Correct typo of ----show-screenshot

---

packages/cli/report-tsconfig.json
packages/cli/src/cmd/run.ts

**Problem:** HTML report cannot be created in production due to:
- Incorrect report template path
- An error when `webpack` processes `tsconfig.json` of the package `@flood/element-cli`
**Solution**:
- Correct the path to report template
- Create a custom `tsconfig.json` for compiling HTML report

fix: cannot create html report

---

packages/core/src/ElementOption.ts

Resolve issue [FLO-2172](https://tricentisflood.atlassian.net/browse/FLO-2172).

[Element 2.0] Fix test that can not show image on iTerm2 when folder has the element config file

---

packages/core/src/Element.ts

Apply custom console when running on Flood, which contains the missing method `setGroupDept`

fix: fail to start 2nd iteration when running on Flood

---

packages/core/package.json

The `@flood/element-core` package currently has a vulnerable dependency (`highlight.js`) due to its dependency on the `typedoc` package.  Looking a little closer, it seems like `typedoc` is only used during development.  If I'm right about that, an easy solution is just to move it to `devDependencies`, and save everyone the extra packages.

Move typedoc to devDependency of element-core

---

lerna.json
package.json
packages/cli/package.json
packages/compiler/package.json
packages/core/package.json
packages/docs/package.json
packages/element-api/package.json
packages/element-cli/package.json
packages/element-scheduler/package.json
packages/element/package.json
packages/flood-runner/package.json

My bad at the **[PR#470](https://github.com/flood-io/element/pull/470)**. Version 2.0.5-canary.1 exists so the Github actions can not publish 2.0.5-canary.1 again.

[Element Canary] Correct packages's canary version

---

packages/docs/versioned_docs/version-1.3/guides/TestData.md

The "Flood challenge with test data" in the "Using Test Data" guide had the wrong syntax and didn't point anywhere.
This was in the "More information" section at the very bottom.
https://element.flood.io/docs/guides/test-data#more-information
This change point "Flood challenge with test data" to the example script at https://github.com/flood-io/element/blob/master/examples/flood-challenge.ts

fix: correct link in test data guide

---

.github/workflows/codeql-analysis.yml
.github/workflows/lerna-stable.yml
DEVELOPMENT.md
VERSIONING.md
examples/automation/run-all/flood-runall.sh
lerna.json
packages/core/src/test-data/Loader.ts
packages/docs/docusaurus.config.js
packages/docs/versioned_docs/version-1.0/guides/TestData.md
packages/docs/versioned_docs/version-1.3/guides/TestData.md
packages/docs/versioned_docs/version-1.5/guides/TestData.md
packages/docs/versioned_docs/version-2.0/guides/TestData.md

The default branch on GH is now `canary`, since this is where PRs should go.
This re-names references to the `master` branch to `stable`, which makes more sense given the other meta version branches are named after their releases (`canary` and `beta`).

refactor: rename master to stable

---

packages/core/src/runtime/test-observers/LifecycleObserver.ts
packages/flood-runner/src/Grid.ts

I'm doing this so I can rule in/out these changes for causing the logging problems we're facing with 2.0.

fix: revert the timing observer to tracing observer change for flood-runner

---

packages/cli/src/utils/updateCheck.ts

Until we resolve some issues in 2.x

Disable printing the update to 2.x message

---

packages/core/src/runtime/test-observers/TimingObserver.ts

Some customers have experienced a handful of large negative response time values being recorded, which sometimes resulted in negative mean response time for a given flood. The root cause is still unknown, but this should prevent those measurements from being recorded.

fix: guard against negative response time measurements
